function LoadJobPrice()
{
    cache_get_value_name_int(0, "sjforklift", sjforklift);
    cache_get_value_name_int(0, "sjmower", sjmower);
    cache_get_value_name_int(0, "sjsweeper", sjsweeper);
    cache_get_value_name_int(0, "sjbus", sjbus);
    cache_get_value_name_int(0, "sjtrashmaster", sjtrashmaster);
    cache_get_value_name_int(0, "jobpizza", jobpizzaprice);
    cache_get_value_name_int(0, "jobbutcher", jobbutcherprice);
    cache_get_value_name_int(0, "jobpemerassusu",jobpemerahprice);
    cache_get_value_name_int(0, "jobreflenish", jobreflenishprice);
    cache_get_value_name_int(0, "jobtrucker", jobtruckerprice);
    cache_get_value_name_int(0, "drugdealer1", drugdealerprice1);
    cache_get_value_name_int(0, "drugdealer2", drugdealerprice2);
    cache_get_value_name_int(0, "drugdealer3", drugdealerprice3);
    cache_get_value_name_int(0, "jobminer", jobminerprice);
    cache_get_value_name_int(0, "production1", productprice1);
    cache_get_value_name_int(0, "production2", productprice2);
    cache_get_value_name_int(0, "production3", productprice3);
    cache_get_value_name_int(0, "hauling1", haulingprice1);
    cache_get_value_name_int(0, "hauling2", haulingprice2);
    cache_get_value_name_int(0, "hauling3", haulingprice3);
    cache_get_value_name_int(0, "factionprice", factionprice);
}