#define MAX_VOUCHER 50

#define MAX_ASKS 50

#define MAX_REPORTS 50

#define MAX_DROP_WEAPON 50

#define MAX_ACTOR 50

#define MAX_ATM 50

#define MAX_BISNIS 50

#define MAX_DEALER 50

#define MAX_SVPOINT 50

#define MAX_FACTIONVEH 50

#define MAX_FAMILY 5

#define MAX_GARKOT 50

#define MAX_GATES 50

#define MAX_HOUSES	50
#define LIMIT_PER_PLAYER 3

#define MAX_LOCKERS	50

#define MAX_MAPO_OBJECT 100

#define MAX_NPCFAM 50

#define MAX_PEDAGANG 10
#define MAX_PDG_INT 7000

#define MAX_PFARM 50

#define MAX_RENTAL 50

#define MAX_SIGNAL 50

#define MAX_SPEEDCAM 50

#define MAX_TAGS	50

#define MAX_MATEXT 50

#define MAX_VENDING 50

#define MAX_WORKSHOP 50

#define MAX_DYNAMIC_BARRICADES	100

#define MAX_FACCALL 50

#define MAX_SPIKESTRIPS 50

#define MAX_ADSLOG 50

#define MAX_BILLS 500

#define MAX_BOOMBOX 50

#define MAX_DAMAGE 500

#define MAX_NOTES 3

#define MAX_PAYPHONE 500

#define MAX_STORAGE 500

#define MAX_UCP 3

#define MAX_PLANT 10000

#define MAX_TREES 100
#define TREE_RESPAWN 1800

#define MAX_TRASH 500

#define MAX_GSTATION 50

#define MAX_CAR_STORAGE 5