new PlayerText:DeathNTRP[MAX_PLAYERS][8];

//new PlayerText: Logobaru[MAX_PLAYERS][18];

new PlayerText: SpeedoPakCik[MAX_PLAYERS][17];

new PlayerText:NatKTP[MAX_PLAYERS][28];

new PlayerText:NatDriveLic[MAX_PLAYERS][25];

new PlayerText:Time[MAX_PLAYERS][1];

new PlayerText:ActiveTD[MAX_PLAYERS];

new PlayerText: ShootFire[MAX_PLAYERS][6];

new PlayerText: RadialMenuHytam[MAX_PLAYERS][53];

new PlayerText: notipcenter[MAX_PLAYERS][1];

new PlayerText: hbeexp[MAX_PLAYERS][39];

new PlayerText: voicemenu[MAX_PLAYERS][8];
