new PlayerText: INVINFO[MAX_PLAYERS][33];
new PlayerText: NAMETD[MAX_PLAYERS][16];
new PlayerText: INDEXTD[MAX_PLAYERS][16];
new PlayerText: MODELTD[MAX_PLAYERS][16];
new PlayerText: AMOUNTTD[MAX_PLAYERS][16];
new PlayerText: GARISBAWAH[MAX_PLAYERS][16];

INVINFO[playerid][0] = CreatePlayerTextDraw(playerid, 270.000, 628.000, "Gambar teks baru");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][0], 0.300, 1.500);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][0], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][0], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][0], 1);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][0], 1);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][0], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][0], 1);

INVINFO[playerid][1] = CreatePlayerTextDraw(playerid, 109.000, 101.000, "_");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][1], 24.000, 26.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][1], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][1], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][1], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][1], 0);
PlayerTextDrawFont(playerid, INVINFO[playerid][1], 5);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][1], 0);
PlayerTextDrawSetPreviewModel(playerid, INVINFO[playerid][1], 2751);
PlayerTextDrawSetPreviewRot(playerid, INVINFO[playerid][1], -90.000, 0.000, 30.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, INVINFO[playerid][1], 0, 0);

INVINFO[playerid][2] = CreatePlayerTextDraw(playerid, 115.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][2], 6.000, 7.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][2], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][2], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][2], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][2], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][2], 1);

INVINFO[playerid][3] = CreatePlayerTextDraw(playerid, 160.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][3], 6.000, 7.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][3], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][3], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][3], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][3], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][3], 1);

INVINFO[playerid][4] = CreatePlayerTextDraw(playerid, 205.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][4], 6.000, 7.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][4], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][4], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][4], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][4], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][4], 1);

INVINFO[playerid][5] = CreatePlayerTextDraw(playerid, 250.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][5], 6.000, 7.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][5], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][5], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][5], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][5], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][5], 1);

INVINFO[playerid][6] = CreatePlayerTextDraw(playerid, 117.000, 129.000, "1");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][6], 0.070, 0.597);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][6], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][6], 502316031);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][6], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][6], 2);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][6], 1);

INVINFO[playerid][7] = CreatePlayerTextDraw(playerid, 162.000, 129.000, "2");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][7], 0.070, 0.597);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][7], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][7], 502316031);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][7], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][7], 2);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][7], 1);

INVINFO[playerid][8] = CreatePlayerTextDraw(playerid, 207.000, 129.000, "3");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][8], 0.070, 0.597);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][8], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][8], 502316031);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][8], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][8], 2);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][8], 1);

INVINFO[playerid][9] = CreatePlayerTextDraw(playerid, 252.000, 129.000, "4");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][9], 0.070, 0.597);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][9], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][9], 502316031);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][9], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][9], 2);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][9], 1);

INVINFO[playerid][10] = CreatePlayerTextDraw(playerid, 314.000, 204.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][10], 47.000, 43.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][10], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][10], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][10], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][10], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, INVINFO[playerid][10], 1);

INVINFO[playerid][11] = CreatePlayerTextDraw(playerid, 305.000, 166.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][11], 66.000, 139.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][11], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][11], 100);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][11], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][11], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][11], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][11], 1);

INVINFO[playerid][12] = CreatePlayerTextDraw(playerid, 314.000, 282.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][12], 47.000, 18.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][12], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][12], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][12], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][12], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, INVINFO[playerid][12], 1);

INVINFO[playerid][13] = CreatePlayerTextDraw(playerid, 314.000, 258.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][13], 47.000, 18.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][13], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][13], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][13], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][13], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, INVINFO[playerid][13], 1);

INVINFO[playerid][14] = CreatePlayerTextDraw(playerid, 314.000, 171.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][14], 47.000, 18.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][14], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][14], 502315876);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][14], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][14], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, INVINFO[playerid][14], 1);

INVINFO[playerid][15] = CreatePlayerTextDraw(playerid, 326.000, 225.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][15], 13.000, 7.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][15], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][15], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][15], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][15], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][15], 1);

INVINFO[playerid][16] = CreatePlayerTextDraw(playerid, 339.000, 227.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][16], 7.000, 5.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][16], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][16], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][16], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][16], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][16], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][16], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][16], 1);

INVINFO[playerid][17] = CreatePlayerTextDraw(playerid, 342.000, 220.000, "/");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][17], 0.759, 1.299);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][17], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][17], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][17], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][17], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][17], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][17], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][17], 1);

INVINFO[playerid][18] = CreatePlayerTextDraw(playerid, 327.000, 220.000, "/");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][18], 0.619, 0.898);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][18], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][18], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][18], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][18], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][18], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][18], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][18], 1);

INVINFO[playerid][19] = CreatePlayerTextDraw(playerid, 333.000, 222.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][19], 9.000, 3.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][19], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][19], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][19], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][19], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][19], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][19], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][19], 1);

INVINFO[playerid][20] = CreatePlayerTextDraw(playerid, 340.000, 221.000, "LD_BEAT:chit");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][20], 5.000, 5.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][20], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][20], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][20], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][20], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][20], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][20], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][20], 1);

INVINFO[playerid][21] = CreatePlayerTextDraw(playerid, 348.000, 220.000, "LD_BEAT:chit");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][21], 5.000, 5.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][21], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][21], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][21], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][21], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][21], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][21], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][21], 1);

INVINFO[playerid][22] = CreatePlayerTextDraw(playerid, 328.000, 175.000, "Amount");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][22], 0.150, 0.999);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][22], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][22], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][22], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][22], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][22], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][22], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][22], 1);

INVINFO[playerid][23] = CreatePlayerTextDraw(playerid, 331.000, 261.000, "Give");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][23], 0.158, 1.098);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][23], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][23], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][23], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][23], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][23], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][23], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][23], 1);

INVINFO[playerid][24] = CreatePlayerTextDraw(playerid, 331.000, 285.000, "Close");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][24], 0.158, 0.999);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][24], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][24], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][24], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][24], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][24], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][24], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][24], 1);

INVINFO[playerid][25] = CreatePlayerTextDraw(playerid, 332.000, 207.000, "Use");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][25], 0.180, 1.098);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][25], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][25], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][25], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][25], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][25], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][25], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][25], 1);

INVINFO[playerid][26] = CreatePlayerTextDraw(playerid, 296.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][26], 6.000, 215.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][26], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][26], 100);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][26], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][26], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][26], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][26], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][26], 1);

INVINFO[playerid][27] = CreatePlayerTextDraw(playerid, 297.000, 130.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][27], 4.000, 110.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][27], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][27], 100);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][27], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][27], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][27], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][27], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][27], 1);
PlayerTextDrawSetSelectable(playerid, INVINFO[playerid][27], 1);

INVINFO[playerid][28] = CreatePlayerTextDraw(playerid, 297.000, 240.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][28], 4.000, 103.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][28], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][28], 100);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][28], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][28], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][28], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][28], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][28], 1);
PlayerTextDrawSetSelectable(playerid, INVINFO[playerid][28], 1);

INVINFO[playerid][29] = CreatePlayerTextDraw(playerid, 250.000, 111.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INVINFO[playerid][29], 43.000, 12.000);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][29], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][29], 100);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][29], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][29], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][29], 255);
PlayerTextDrawFont(playerid, INVINFO[playerid][29], 4);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][29], 1);

INVINFO[playerid][30] = CreatePlayerTextDraw(playerid, 132.000, 107.000, "Player");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][30], 0.158, 0.999);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][30], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][30], 502316031);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][30], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][30], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][30], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][30], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][30], 1);

INVINFO[playerid][31] = CreatePlayerTextDraw(playerid, 131.000, 117.000, "16.00/50.00kg");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][31], 0.108, 0.699);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][31], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][31], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][31], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][31], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][31], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][31], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][31], 1);

INVINFO[playerid][32] = CreatePlayerTextDraw(playerid, 257.000, 113.000, "Jaden_Bakteria");
PlayerTextDrawLetterSize(playerid, INVINFO[playerid][32], 0.119, 0.799);
PlayerTextDrawAlignment(playerid, INVINFO[playerid][32], 1);
PlayerTextDrawColor(playerid, INVINFO[playerid][32], -1);
PlayerTextDrawSetShadow(playerid, INVINFO[playerid][32], 0);
PlayerTextDrawSetOutline(playerid, INVINFO[playerid][32], 0);
PlayerTextDrawBackgroundColor(playerid, INVINFO[playerid][32], 150);
PlayerTextDrawFont(playerid, INVINFO[playerid][32], 1);
PlayerTextDrawSetProportional(playerid, INVINFO[playerid][32], 1);


NAMETD[playerid][0] = CreatePlayerTextDraw(playerid, 117.000, 172.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][0], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][0], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][0], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][0], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][0], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][0], 1);

NAMETD[playerid][1] = CreatePlayerTextDraw(playerid, 162.000, 172.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][1], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][1], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][1], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][1], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][1], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][1], 1);

NAMETD[playerid][2] = CreatePlayerTextDraw(playerid, 207.000, 172.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][2], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][2], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][2], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][2], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][2], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][2], 1);

NAMETD[playerid][3] = CreatePlayerTextDraw(playerid, 252.000, 172.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][3], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][3], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][3], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][3], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][3], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][3], 1);

NAMETD[playerid][4] = CreatePlayerTextDraw(playerid, 117.000, 226.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][4], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][4], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][4], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][4], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][4], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][4], 1);

NAMETD[playerid][5] = CreatePlayerTextDraw(playerid, 162.000, 226.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][5], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][5], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][5], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][5], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][5], 1);

NAMETD[playerid][6] = CreatePlayerTextDraw(playerid, 207.000, 226.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][6], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][6], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][6], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][6], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][6], 1);

NAMETD[playerid][7] = CreatePlayerTextDraw(playerid, 252.000, 226.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][7], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][7], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][7], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][7], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][7], 1);

NAMETD[playerid][8] = CreatePlayerTextDraw(playerid, 117.000, 280.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][8], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][8], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][8], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][8], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][8], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][8], 1);

NAMETD[playerid][9] = CreatePlayerTextDraw(playerid, 162.000, 280.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][9], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][9], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][9], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][9], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][9], 1);

NAMETD[playerid][10] = CreatePlayerTextDraw(playerid, 207.000, 280.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][10], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][10], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][10], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][10], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][10], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][10], 1);

NAMETD[playerid][11] = CreatePlayerTextDraw(playerid, 252.000, 280.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][11], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][11], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][11], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][11], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][11], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][11], 1);

NAMETD[playerid][12] = CreatePlayerTextDraw(playerid, 117.000, 335.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][12], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][12], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][12], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][12], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][12], 1);

NAMETD[playerid][13] = CreatePlayerTextDraw(playerid, 162.000, 335.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][13], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][13], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][13], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][13], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][13], 1);

NAMETD[playerid][14] = CreatePlayerTextDraw(playerid, 207.000, 335.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][14], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][14], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][14], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][14], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][14], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][14], 1);

NAMETD[playerid][15] = CreatePlayerTextDraw(playerid, 252.000, 335.000, "Water");
PlayerTextDrawLetterSize(playerid, NAMETD[playerid][15], 0.100, 0.598);
PlayerTextDrawAlignment(playerid, NAMETD[playerid][15], 1);
PlayerTextDrawColor(playerid, NAMETD[playerid][15], -1);
PlayerTextDrawSetShadow(playerid, NAMETD[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, NAMETD[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid][15], 150);
PlayerTextDrawFont(playerid, NAMETD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, NAMETD[playerid][15], 1);

INDEXTD[playerid][0] = CreatePlayerTextDraw(playerid, 115.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][0], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][0], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][0], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][0], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][0], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][0], 1);

INDEXTD[playerid][1] = CreatePlayerTextDraw(playerid, 160.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][1], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][1], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][1], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][1], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][1], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][1], 1);

INDEXTD[playerid][2] = CreatePlayerTextDraw(playerid, 205.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][2], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][2], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][2], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][2], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][2], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][2], 1);

INDEXTD[playerid][3] = CreatePlayerTextDraw(playerid, 250.000, 129.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][3], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][3], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][3], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][3], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][3], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][3], 1);

INDEXTD[playerid][4] = CreatePlayerTextDraw(playerid, 115.000, 183.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][4], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][4], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][4], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][4], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][4], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][4], 1);

INDEXTD[playerid][5] = CreatePlayerTextDraw(playerid, 160.000, 183.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][5], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][5], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][5], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][5], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][5], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][5], 1);

INDEXTD[playerid][6] = CreatePlayerTextDraw(playerid, 205.000, 183.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][6], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][6], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][6], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][6], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][6], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][6], 1);

INDEXTD[playerid][7] = CreatePlayerTextDraw(playerid, 250.000, 183.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][7], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][7], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][7], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][7], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][7], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][7], 1);

INDEXTD[playerid][8] = CreatePlayerTextDraw(playerid, 115.000, 237.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][8], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][8], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][8], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][8], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][8], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][8], 1);

INDEXTD[playerid][9] = CreatePlayerTextDraw(playerid, 160.000, 237.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][9], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][9], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][9], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][9], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][9], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][9], 1);

INDEXTD[playerid][10] = CreatePlayerTextDraw(playerid, 205.000, 237.000, "LD_BUM:blkdot"); //GUNAKAN
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][10], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][10], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][10], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][10], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][10], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][10], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][10], 1);

INDEXTD[playerid][11] = CreatePlayerTextDraw(playerid, 250.000, 237.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][11], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][11], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][11], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][11], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][11], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][11], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][11], 1);

INDEXTD[playerid][12] = CreatePlayerTextDraw(playerid, 115.000, 291.000, "LD_BUM:blkdot"); //MENUTUP
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][12], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][12], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][12], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][12], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][12], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][12], 1);

INDEXTD[playerid][13] = CreatePlayerTextDraw(playerid, 160.000, 291.000, "LD_BUM:blkdot"); //MEMBERIKAN     
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][13], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][13], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][13], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][13], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][13], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][13], 1);

INDEXTD[playerid][14] = CreatePlayerTextDraw(playerid, 205.000, 291.000, "LD_BUM:blkdot"); //JUMLAH
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][14], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][14], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][14], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][14], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][14], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][14], 1);

INDEXTD[playerid][15] = CreatePlayerTextDraw(playerid, 250.000, 291.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, INDEXTD[playerid][15], 43.000, 52.000);
PlayerTextDrawAlignment(playerid, INDEXTD[playerid][15], 1);
PlayerTextDrawColor(playerid, INDEXTD[playerid][15], 100);
PlayerTextDrawSetShadow(playerid, INDEXTD[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, INDEXTD[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, INDEXTD[playerid][15], 255);
PlayerTextDrawFont(playerid, INDEXTD[playerid][15], 4);
PlayerTextDrawSetProportional(playerid, INDEXTD[playerid][15], 1);
PlayerTextDrawSetSelectable(playerid, INDEXTD[playerid][15], 1);

MODELTD[playerid][0] = CreatePlayerTextDraw(playerid, 119.000, 134.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][0], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][0], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][0], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][0], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][0], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][0], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][0], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][0], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][0], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][0], 0, 0);

MODELTD[playerid][1] = CreatePlayerTextDraw(playerid, 164.000, 134.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][1], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][1], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][1], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][1], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][1], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][1], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][1], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][1], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][1], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][1], 0, 0);

MODELTD[playerid][2] = CreatePlayerTextDraw(playerid, 208.000, 134.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][2], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][2], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][2], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][2], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][2], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][2], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][2], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][2], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][2], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][2], 0, 0);

MODELTD[playerid][3] = CreatePlayerTextDraw(playerid, 254.000, 134.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][3], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][3], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][3], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][3], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][3], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][3], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][3], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][3], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][3], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][3], 0, 0);

MODELTD[playerid][4] = CreatePlayerTextDraw(playerid, 119.000, 189.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][4], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][4], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][4], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][4], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][4], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][4], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][4], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][4], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][4], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][4], 0, 0);

MODELTD[playerid][5] = CreatePlayerTextDraw(playerid, 164.000, 189.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][5], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][5], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][5], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][5], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][5], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][5], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][5], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][5], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][5], 0, 0);

MODELTD[playerid][6] = CreatePlayerTextDraw(playerid, 208.000, 189.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][6], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][6], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][6], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][6], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][6], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][6], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][6], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][6], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][6], 0, 0);

MODELTD[playerid][7] = CreatePlayerTextDraw(playerid, 254.000, 189.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][7], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][7], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][7], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][7], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][7], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][7], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][7], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][7], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][7], 0, 0);

MODELTD[playerid][8] = CreatePlayerTextDraw(playerid, 119.000, 242.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][8], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][8], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][8], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][8], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][8], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][8], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][8], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][8], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][8], 0, 0);

MODELTD[playerid][9] = CreatePlayerTextDraw(playerid, 164.000, 242.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][9], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][9], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][9], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][9], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][9], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][9], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][9], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][9], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][9], 0, 0);

MODELTD[playerid][10] = CreatePlayerTextDraw(playerid, 208.000, 242.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][10], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][10], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][10], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][10], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][10], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][10], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][10], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][10], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][10], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][10], 0, 0);

MODELTD[playerid][11] = CreatePlayerTextDraw(playerid, 254.000, 242.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][11], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][11], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][11], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][11], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][11], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][11], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][11], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][11], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][11], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][11], 0, 0);

MODELTD[playerid][12] = CreatePlayerTextDraw(playerid, 119.000, 296.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][12], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][12], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][12], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][12], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][12], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][12], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][12], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][12], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][12], 0, 0);

MODELTD[playerid][13] = CreatePlayerTextDraw(playerid, 164.000, 296.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][13], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][13], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][13], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][13], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][13], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][13], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][13], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][13], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][13], 0, 0);

MODELTD[playerid][14] = CreatePlayerTextDraw(playerid, 208.000, 296.000, "_");
PlayerTextDrawTextSize(playerid, MODELTD[playerid][14], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][14], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][14], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][14], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][14], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][14], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][14], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][14], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][14], 0, 0);

MODELTD[playerid][15] = CreatePlayerTextDraw(playerid, 254.000, 296.000, "_"); 
PlayerTextDrawTextSize(playerid, MODELTD[playerid][15], 32.000, 39.000);
PlayerTextDrawAlignment(playerid, MODELTD[playerid][15], 1);
PlayerTextDrawColor(playerid, MODELTD[playerid][15], -1);
PlayerTextDrawSetShadow(playerid, MODELTD[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, MODELTD[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, MODELTD[playerid][15], 0);
PlayerTextDrawFont(playerid, MODELTD[playerid][15], 5);
PlayerTextDrawSetProportional(playerid, MODELTD[playerid][15], 0);
PlayerTextDrawSetPreviewModel(playerid, MODELTD[playerid][15], 3026);
PlayerTextDrawSetPreviewRot(playerid, MODELTD[playerid][15], 0.000, 0.000, 0.000, 1.000);
PlayerTextDrawSetPreviewVehCol(playerid, MODELTD[playerid][15], 0, 0);

AMOUNTTD[playerid][0] = CreatePlayerTextDraw(playerid, 143.000, 131.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][0], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][0], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][0], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][0], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][0], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][0], 1);

AMOUNTTD[playerid][1] = CreatePlayerTextDraw(playerid, 189.000, 131.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][1], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][1], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][1], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][1], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][1], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][1], 1);

AMOUNTTD[playerid][2] = CreatePlayerTextDraw(playerid, 234.000, 131.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][2], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][2], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][2], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][2], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][2], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][2], 1);

AMOUNTTD[playerid][3] = CreatePlayerTextDraw(playerid, 279.000, 131.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][3], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][3], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][3], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][3], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][3], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][3], 1);

AMOUNTTD[playerid][4] = CreatePlayerTextDraw(playerid, 143.000, 185.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][4], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][4], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][4], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][4], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][4], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][4], 1);

AMOUNTTD[playerid][5] = CreatePlayerTextDraw(playerid, 189.000, 185.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][5], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][5], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][5], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][5], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][5], 1);

AMOUNTTD[playerid][6] = CreatePlayerTextDraw(playerid, 234.000, 185.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][6], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][6], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][6], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][6], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][6], 1);

AMOUNTTD[playerid][7] = CreatePlayerTextDraw(playerid, 279.000, 185.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][7], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][7], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][7], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][7], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][7], 1);

AMOUNTTD[playerid][8] = CreatePlayerTextDraw(playerid, 143.000, 239.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][8], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][8], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][8], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][8], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][8], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][8], 1);

AMOUNTTD[playerid][9] = CreatePlayerTextDraw(playerid, 189.000, 239.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][9], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][9], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][9], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][9], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][9], 1);

AMOUNTTD[playerid][10] = CreatePlayerTextDraw(playerid, 234.000, 239.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][10], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][10], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][10], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][10], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][10], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][10], 1);

AMOUNTTD[playerid][11] = CreatePlayerTextDraw(playerid, 279.000, 239.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][11], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][11], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][11], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][11], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][11], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][11], 1);

AMOUNTTD[playerid][12] = CreatePlayerTextDraw(playerid, 143.000, 293.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][12], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][12], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][12], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][12], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][12], 1);

AMOUNTTD[playerid][13] = CreatePlayerTextDraw(playerid, 189.000, 293.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][13], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][13], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][13], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][13], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][13], 1);

AMOUNTTD[playerid][14] = CreatePlayerTextDraw(playerid, 234.000, 293.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][14], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][14], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][14], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][14], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][14], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][14], 1);

AMOUNTTD[playerid][15] = CreatePlayerTextDraw(playerid, 279.000, 293.000, "1 (1.00)");
PlayerTextDrawLetterSize(playerid, AMOUNTTD[playerid][15], 0.100, 0.499);
PlayerTextDrawAlignment(playerid, AMOUNTTD[playerid][15], 1);
PlayerTextDrawColor(playerid, AMOUNTTD[playerid][15], -1);
PlayerTextDrawSetShadow(playerid, AMOUNTTD[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, AMOUNTTD[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, AMOUNTTD[playerid][15], 150);
PlayerTextDrawFont(playerid, AMOUNTTD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, AMOUNTTD[playerid][15], 1);

GARISBAWAH[playerid][0] = CreatePlayerTextDraw(playerid, 115.000, 179.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][0], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][0], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][0], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][0], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][0], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][0], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][0], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][0], 1);

GARISBAWAH[playerid][1] = CreatePlayerTextDraw(playerid, 160.000, 179.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][1], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][1], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][1], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][1], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][1], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][1], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][1], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][1], 1);

GARISBAWAH[playerid][2] = CreatePlayerTextDraw(playerid, 205.000, 179.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][2], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][2], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][2], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][2], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][2], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][2], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][2], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][2], 1);

GARISBAWAH[playerid][3] = CreatePlayerTextDraw(playerid, 250.000, 179.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][3], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][3], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][3], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][3], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][3], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][3], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][3], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][3], 1);

GARISBAWAH[playerid][4] = CreatePlayerTextDraw(playerid, 115.000, 233.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][4], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][4], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][4], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][4], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][4], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][4], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][4], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][4], 1);

GARISBAWAH[playerid][5] = CreatePlayerTextDraw(playerid, 160.000, 233.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][5], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][5], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][5], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][5], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][5], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][5], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][5], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][5], 1);

GARISBAWAH[playerid][6] = CreatePlayerTextDraw(playerid, 205.000, 233.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][6], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][6], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][6], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][6], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][6], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][6], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][6], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][6], 1);

GARISBAWAH[playerid][7] = CreatePlayerTextDraw(playerid, 250.000, 233.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][7], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][7], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][7], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][7], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][7], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][7], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][7], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][7], 1);

GARISBAWAH[playerid][8] = CreatePlayerTextDraw(playerid, 115.000, 287.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][8], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][8], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][8], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][8], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][8], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][8], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][8], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][8], 1);

GARISBAWAH[playerid][9] = CreatePlayerTextDraw(playerid, 160.000, 287.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][9], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][9], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][9], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][9], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][9], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][9], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][9], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][9], 1);

GARISBAWAH[playerid][10] = CreatePlayerTextDraw(playerid, 205.000, 287.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][10], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][10], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][10], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][10], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][10], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][10], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][10], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][10], 1);

GARISBAWAH[playerid][11] = CreatePlayerTextDraw(playerid, 250.000, 287.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][11], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][11], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][11], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][11], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][11], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][11], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][11], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][11], 1);

GARISBAWAH[playerid][12] = CreatePlayerTextDraw(playerid, 115.000, 342.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][12], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][12], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][12], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][12], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][12], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][12], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][12], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][12], 1);

GARISBAWAH[playerid][13] = CreatePlayerTextDraw(playerid, 160.000, 342.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][13], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][13], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][13], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][13], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][13], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][13], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][13], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][13], 1);

GARISBAWAH[playerid][14] = CreatePlayerTextDraw(playerid, 205.000, 342.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][14], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][14], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][14], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][14], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][14], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][14], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][14], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][14], 1);

GARISBAWAH[playerid][15] = CreatePlayerTextDraw(playerid, 250.000, 342.000, "LD_BUM:blkdot");
PlayerTextDrawTextSize(playerid, GARISBAWAH[playerid][15], 43.000, 2.000);
PlayerTextDrawAlignment(playerid, GARISBAWAH[playerid][15], 1);
PlayerTextDrawColor(playerid, GARISBAWAH[playerid][15], 502316031);
PlayerTextDrawSetShadow(playerid, GARISBAWAH[playerid][15], 0);
PlayerTextDrawSetOutline(playerid, GARISBAWAH[playerid][15], 0);
PlayerTextDrawBackgroundColor(playerid, GARISBAWAH[playerid][15], 255);
PlayerTextDrawFont(playerid, GARISBAWAH[playerid][15], 4);
PlayerTextDrawSetProportional(playerid, GARISBAWAH[playerid][15], 1);
